New programming lectures
MIPT-Group/Lectures_Tex_Club pull request #11
Opened 2020-09-29 19:26 UTC by NikitaEvs

- Added lectures 1,2
- Some fixes in lecture 1.
- Some fixes in the title.

2020-10-04 07:59 UTC, MarkTiukov requested changes
Посмотрел 2ю лекцию. Третью позже посмотрю, чтобы серьезно на формуле и тп посмотреть. 
Что скажешь по второй?

2020-10-04 08:09 UTC, NikitaEvs commented on Lectures/3_Semester/Programming_introduction/lectures/lec02.tex
> +\subsection{Структура данных Бор.}
Да, поправлю сейчас

2020-10-04 08:10 UTC, NikitaEvs commented on Lectures/3_Semester/Programming_introduction/lectures/lec02.tex
> +метку на вершине, в которую дошли.
Хм, думал провести аналогию с кодом, но сейчас поправлю, если бьёт по глазам

2020-10-04 08:10 UTC, NikitaEvs commented on Lectures/3_Semester/Programming_introduction/lectures/lec02.tex
> +\highlight{Ахо-Корасик.}
Хорошо

2020-10-07 22:08 UTC, NikitaEvs commented
- Added raw 4th lecture

2020-10-09 13:02 UTC, MarkTiukov requested changes
Если будешь начинать пятую лекцию, мб стоит создать новую ветку от данной, чтобы уже влить эту в мейн рано или поздно:)

Скоро посмотрю 4ую, пока третью чекнул

2020-10-09 13:02 UTC, MarkTiukov commented on Lectures/3_Semester/Programming_introduction/lectures/lec03.tex
> +происходит за  $O(1)$.
Суффмас убивает...
Я не смог прям вчитаться в док-во, попытался просто описки в словах найти. Надеюсь получилось

2020-10-20 22:53 UTC, NikitaEvs commented on Lectures/3_Semester/Programming_introduction/lectures/lec03.tex
> +       \end{lemma}
Хм, думаю, в этом есть смысл, во многих конспектах так делают

2020-10-20 22:55 UTC, NikitaEvs commented on Lectures/3_Semester/Programming_introduction/lectures/lec03.tex
> +происходит за  $O(1)$.
Да, там смерть
Что-то я часто стал случайно путать ться/тся :(

2020-10-21 10:01 UTC, NikitaEvs commented
5 лекцию в отдельный PR тогда вынесу

2020-11-08 23:17 UTC, MarkTiukov approved these changes

2020-11-08 23:22 UTC, merged